#!/bin/bash

BOOT0=17
RST=23
GPIOCHIP=0
STM32FLASH='stm32flash'
BINFILE='wombat.bin'
DEV='/dev/ttyAMA0'

if [ $# -ne 0 ]; then
    BINFILE=$1
fi

# Initialize GPIOs
if ! ./wallaby_init_gpio; then
    echo "Failed to initialize GPIOs."
    exit 1
fi

# set BOOT0 high so we stay in the bootloader on reboot
echo "Setting BOOT0 high..."
gpioset gpiochip${GPIOCHIP} ${BOOT0}=1

# reset co-processor
./wallaby_reset_coproc

# Program the device
sleep 1
echo "Flashing firmware..."
CMD="${STM32FLASH} -v -S 0x08000000 -w ${BINFILE} ${DEV}"
echo $CMD
eval $CMD

# Set BOOT0 low to run the program after reset
echo "Setting BOOT0 low..."
gpioset gpiochip${GPIOCHIP} ${BOOT0}=0
sleep 1

# Reset co-processor again
./wallaby_reset_coproc

echo "Flashing process completed."